FROM gcr.io/cadvisor/cadvisor:v0.47.2
# FROM  debian:bullseye

# RUN apt-get update && apt-get install -y wget procps \
# 	&& rm -rf /var/lib/apt/lists/*

# RUN wget https://github.com/google/cadvisor/releases/download/v0.52.1/cadvisor-v0.52.1-linux-amd64 -O cadvisor && \
#     chmod +x cadvisor && \
#     mv cadvisor /usr/local/bin/cadvisor

# CMD ["/usr/local/bin/cadvisor", "-port=8080"]