services:
  gateaway: # entrypoint for services
    container_name: gateaway
    build: ./gateaway
    ports:
      - "8443:8443"
    restart: always
    env_file: .env
    volumes:
      - frontdata:/usr/share/nginx/html:ro
    depends_on:
      - users
      - game
      - frontend
    networks:
      - tranet

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - "5000:5000" # for development (live-server)
    volumes:
      - frontdata:/app/dist
    networks:
      - tranet

  users:
    build: ./services/users
    container_name: users
    ports:
      - "4000:4000"
    env_file: .env
    restart: always
    volumes:
      - ./services/shared:/app/shared:ro
    networks:
      - tranet

  game:
    build: ./services/game
    container_name: game
    ports:
      - "3001:3001"
    env_file: .env
    restart: always
    volumes:
      - ./services/shared:/app/shared:ro
    networks:
      - tranet
    
  #openapi:
    #build: ./services/openapi
    #ports:
   #   - "8080:8080" # for internal use
  #  networks:
    #  - tranet
    
networks:
  tranet:
    name: tranet
    driver: bridge

volumes:
  frontdata:
    name: frontdata
