services:
  getaway:
    container_name: getaway
    build: ./getaway
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - user_service
      - game_service

  user_service:
    build: ./services/user
    ports:
      - "3002:3002"
    restart: always

  
  game_service:
    build: ./services/game
    ports:
      - "3001:3001"
    restart: always
